### ISSUE TITLE
they are not stealing with this program

### ISSUE THREAD

**Issue by alamarca** [Lunahax/VAL0ADER#7]
evil born modified my host file so that the antivirus does not work I had to format my computer and change all the keys that were taken

https://imgur.com/L71KRbx

**Comment by alamarca** [comment]
friend the stars of this GIT are because they exchange them for KEYS of the cheat it is not because it functions or is safe it is for convenience xd don't be fooled

**Comment by subliMEgg** [comment]
now I understand why you banned me from ds you didn't want me to tell the person that you are modifying their host and you are stealing their accounts xd my god how basic they are

**Comment by Lunahax** [comment]
> now I understand why you banned me from ds you didn't want me to tell the person that you are modifying their host and you are stealing their accounts xd my god how basic they are

💀💀💀💀💀

bro you're 13
literally NO ONE except you is crying
and do you also know why?
because there isn't any harmful shit lmao
i sent you a FA on dc but you declined it so stop the trashtalk and come back when you're mature and finally got some proof lmao

you and all the other 13 year old kids are literally the reason why there's no free version anymore lmao

+ if i would capture cards, why did no one ever lose a single cent? and what would be the sense of a paid version? think about it kid
